/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
*/

export class Euler {
  static run(): void {
    let fib1 = 0;
    let fib2 = 1;
    let sum = 0;

    while (fib2 <= 4000000) {
      if (!(fib2 & 1)) {
        sum += fib2;
      }

      const nextFib = fib1 + fib2;
      fib1 = fib2;
      fib2 = nextFib;
    }

    console.log("SUM: ", sum);
  }
}
